Werkcollege03.Oef02/Models/ErrorViewModel.cs
using System;

namespace Werkcollege03.Oef02.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Werkcollege03.Oef02/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Werkcollege03.Oef02.Models
{
    public class ToDo
    {
        public ToDo()
        {
            Datum = DateTime.Now;
            // seconden en milliseconden op 0 zetten (we gaan er vanuit dat gebruikers to-dos niet op de seconde of milliseconde willen plannen)
            Datum = Datum.AddMilliseconds(-Datum.Millisecond).AddSeconds(-Datum.Second);
        }
        public int ID { get; set; }
        public string Titel { get; set; }
        public DateTime Datum { get; private set; }
        [DataType(DataType.MultilineText)]
        public string Omschrijving { get; set; }
    }
}

Werkcollege03.Oef02/Controllers/ToDosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Werkcollege03.Oef02.Data;
using Werkcollege03.Oef02.Models;

namespace Werkcollege03.Oef02.Controllers
{
    public class ToDosController : Controller
    {
        private readonly Werkcollege03Oef02Context _context;

        public ToDosController(Werkcollege03Oef02Context context)
        {
            _context = context;
        }

        // GET: ToDos
        public async Task<IActionResult> Index()
        {
            return View(await _context.ToDo.ToListAsync());
        }

        // GET: ToDos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDo = await _context.ToDo
                .FirstOrDefaultAsync(m => m.ID == id);
            if (toDo == null)
            {
                return NotFound();
            }

            return View(toDo);
        }

        // GET: ToDos/Create
        public IActionResult Create()
        {
            return View(new ToDo());
        }

        // POST: ToDos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Titel,Datum,Omschrijving")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(toDo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(toDo);
        }

        // GET: ToDos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDo = await _context.ToDo.FindAsync(id);
            if (toDo == null)
            {
                return NotFound();
            }
            return View(toDo);
        }

        // POST: ToDos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Titel,Datum,Omschrijving")] ToDo toDo)
        {
            if (id != toDo.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(toDo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToDoExists(toDo.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(toDo);
        }

        // GET: ToDos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDo = await _context.ToDo
                .FirstOrDefaultAsync(m => m.ID == id);
            if (toDo == null)
            {
                return NotFound();
            }

            return View(toDo);
        }

        // POST: ToDos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var toDo = await _context.ToDo.FindAsync(id);
            _context.ToDo.Remove(toDo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ToDoExists(int id)
        {
            return _context.ToDo.Any(e => e.ID == id);
        }
    }
}

Werkcollege03.Oef02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Werkcollege03.Oef02</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Werkcollege03.Oef02</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDos" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Werkcollege03.Oef02 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Werkcollege03.Oef02/Views/ToDos/Create.cshtml
@model Werkcollege03.Oef02.Models.ToDo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ToDo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titel" class="control-label"></label>
                <input asp-for="Titel" class="form-control" />
                <span asp-validation-for="Titel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Omschrijving" class="control-label"></label>
                <textarea asp-for="Omschrijving" class="form-control"></textarea>
                <span asp-validation-for="Omschrijving" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Werkcollege03.Oef02/Views/ToDos/Delete.cshtml
@model Werkcollege03.Oef02.Models.ToDo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Omschrijving)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Omschrijving)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Werkcollege03.Oef02/Views/ToDos/Details.cshtml
@model Werkcollege03.Oef02.Models.ToDo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Omschrijving)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Omschrijving)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Werkcollege03.Oef02/Views/ToDos/Edit.cshtml
@model Werkcollege03.Oef02.Models.ToDo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Titel" class="control-label"></label>
                <input asp-for="Titel" class="form-control" />
                <span asp-validation-for="Titel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Omschrijving" class="control-label"></label>
                <textarea asp-for="Omschrijving" class="form-control"></textarea>
                <span asp-validation-for="Omschrijving" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Werkcollege03.Oef02/Views/ToDos/Index.cshtml
@model IEnumerable<Werkcollege03.Oef02.Models.ToDo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Datum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Omschrijving)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Datum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Omschrijving)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>